/**
 * @author : LeeZhaoXing
 * @date   : 2021/11/8
 * @desc   :
 */
object Versions {
    const val retrofit = "2.9.0"
    const val okhttpLogging = "3.9.0"
    const val appcompat = "1.2.0"
    const val coreKtx = "1.7.0"
    const val constraintlayout = "2.0.1"
    const val paging = "3.0.0-alpha02"
    const val timber = "4.7.1"
    const val kotlin = "1.3.72"
    const val work = "2.2.0"
    const val room = "2.3.0-alpha01"
    const val cardview = "1.0.0"
    const val recyclerview = "1.1.0"
    const val fragment = "1.3.0-alpha06"
    const val anko = "0.10.8"
    const val swiperefreshlayout = "1.0.0"
    const val hit = "2.28-alpha"
    const val hitViewModule = "1.0.0-alpha01"
    const val material = "1.4.0"
    const val glide = "4.11.0"
    const val viewpager2 = "1.0.0"
    const val lifecycle_version = "2.4.0"
    const val mmkv = "1.2.2"
    const val permissionx = "1.4.0"
    const val liveEventBus = "1.7.2"
    const val leakCanary = "2.7"
    const val gson = "2.8.8"
    const val multidex = "2.0.1"
    const val multitype = "4.2.0"
    const val smartRefreshLayout = "2.0.1"
    const val statusBarUtil = "1.5.1"
    const val epic = "0.11.0"
    const val eventBus = "3.2.0"
    const val router = "1.5.1"
    const val background = "1.6.5"
    const val xpop = "2.4.3"
    const val coil = "1.4.0"
    const val convex = "1.0.0"
    const val activity_ktx = "1.4.0-alpha02"
    const val fragment_ktx = "1.4.0-alpha09"
    const val coordinatorlayout = "1.1.0"
    const val loadSir = "1.3.8"
    const val unpeek_livedata = "7.2.0-beta1"
    const val lottie = "3.5.0"
    const val coroutines = "1.5.2"
    const val autoService = "1.0"
    const val moshi_kotlin="1.12.0"
    const val dokit ="3.5.0"
    const val jsbridge = "1.0.4"
}